/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface NewsletterSignup { 'email' : string, 'timestamp' : Time }
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'image' : string,
  'price' : bigint,
}
export interface Testimonial {
  'content' : string,
  'author' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'addTestimonial' : ActorMethod<[string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInquiry' : ActorMethod<[string, string, string], boolean>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getTestimonialByAuthor' : ActorMethod<[string], [] | [Testimonial]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listInquiries' : ActorMethod<[], Array<Inquiry>>,
  'listNewsletterSignups' : ActorMethod<[], Array<NewsletterSignup>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribeToNewsletter' : ActorMethod<[string], boolean>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'updateTestimonial' : ActorMethod<[string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];